"""empty message

Revision ID: 48549ad14818
Revises: 31319523555e
Create Date: 2021-01-27 19:55:05.097461

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '48549ad14818'
down_revision = '31319523555e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('likes', sa.Column('recipeId', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'likes', 'recipes', ['recipeId'], ['id'])
    op.drop_column('likes', 'timestamp')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('likes', sa.Column('timestamp', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'likes', type_='foreignkey')
    op.drop_column('likes', 'recipeId')
    # ### end Alembic commands ###
