"""empty message

Revision ID: fed5554c9551
Revises: 
Create Date: 2021-01-29 01:06:35.256345

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fed5554c9551'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('likes', sa.Column('id', sa.Integer(), nullable=False))
    op.alter_column('likes', 'recipeId',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('likes', 'userId',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('likes', 'userId',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('likes', 'recipeId',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_column('likes', 'id')
    # ### end Alembic commands ###
